name: Build on Ubuntu

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repository Code
        uses: actions/checkout@v4
      -
        name: Cancel Previous Workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      -
        name: Upgrade Ubuntu Packages
        continue-on-error: true
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq -y upgrade
      -
        name: Configure Git
        continue-on-error: true
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
      -
        name: Clone Repository
        continue-on-error: true
        run: |
          git clone -b tgenc-3 https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} ${{ secrets.GIT_NAME }}
      -
        name: Build and Run Docker
        timeout-minutes: 270
        run: |
          cd ${{ secrets.GIT_NAME }}
          docker build -t tetris .
          docker run tetris
      -
        name: Loop Workflow
        continue-on-error: true
        run: |
          git clone https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:master
