name: GitHub Hosted

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4
      -
        name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      -
        name: Update System
        continue-on-error: true
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq -y upgrade
      -
        name: Initialize Git
        continue-on-error: true
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
      -
        name: Cloning Repository
        continue-on-error: true
        run: |
          git clone -b tgenc-3 https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} tgenc
      -
        name: Running Code
        timeout-minutes: 270
        run: |
          cd tgenc
          docker build -t svtav1enc .
          docker run svtav1enc
      -
        name: Restarting Hosted
        continue-on-error: true
        run: |
          git clone https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "GitHub Hosted: Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
