name: Build on macOS

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4
      -
        name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      -
        name: Set up Docker
        if: runner.os == 'macOS'
        uses: crazy-max/ghaction-setup-docker@v3
      -
        name: Set up Git
        continue-on-error: true
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
      -
        name: Clone Repository
        continue-on-error: true
        run: |
          git clone -b main https://github.com/Nubuki-all/Enc ${{ secrets.GIT_NAME }}
          cd ${{ secrets.GIT_NAME }}
          git clone -b tgenc-3 https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} ${{ secrets.GIT_NAME }}
          rsync -av ${{ secrets.GIT_NAME }}/ .
          rm -rf ${{ secrets.GIT_NAME }}
      -
        name: Run Bot
        timeout-minutes: 270
        continue-on-error: false
        run: |
          cd ${{ secrets.GIT_NAME }}
          docker build . -t master
          docker run master
      -
        name: Loop Workflow
        continue-on-error: true
        run: |
          git clone -b master https://github.com/${{ github.repository }} loop
          cd loop || exit 1
          echo $(date -u +%T%P) >> looper.txt
          git add looper.txt
          git commit -m "Workflow: Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:master
